### ISSUE TITLE
Feature Request: Clear accounting statement

### ISSUE THREAD

**Issue by kikiminou** [stellar/account-viewer-v2#244]
### What problem does your feature solve?

Maintain your own accounts updated and clear

### What would you like to see?

Something like this :

<img width="1551" alt="Capture d’écran 2020-12-19 à 01 24 37" src="https://user-images.githubusercontent.com/20671182/102675385-74c80780-4199-11eb-958e-fe00be3b390f.png">

I would like to see all the amounts (one per operation), including the fees (one per line), and for each asset (separeted).

### What alternatives are there?

I don't know any yet, and accounting with Stellar can give you strong headaches.

Stellar is not very pleasant with accountants. It could even be a hindrance to its use.

By the way your tool is a great start. I especially appreciate the connection with Ledger! And the "send lumens" button is great. I'm so enthousiast with Stellar.

**Comment by quietbits** [comment]
Hello, @kikiminou, thank you for submitting the feature request! Could you please be a little more specific about the change/update you are suggesting?

The Account Viewer is meant to be a very simple tool for Stellar Lumens (XLM) payments only. To view more details on the account, we recommend [StellarExpert](https://stellar.expert/).

**Comment by kikiminou** [comment]
Yes you're right, let's keep it simple.
