### ISSUE TITLE
Albedo sign transaction popup not showing in Safari

### ISSUE THREAD

**Issue by orbitlens** [stellar/account-viewer-v2#273]
We received several emails from users claiming that Albedo sign transaction popup doesn't work in Safari browser.

After digging into this issue I came to conclusion that the reason is a known Safari behavior which blocks popup windows by default unless `window.open()` initiated from the button click handler. `buildPaymentTransaction()` function contains server `fetch` call (inside the `server.loadAccount()` and `server.fetchTimebounds()` methods) which makes Safari to block the popup. At least I believe that's the root of the problem.

Could you please try to call `buildPaymentTransaction()` method **before** showing `ConfirmTransaction.tsx`? Or at least before allowing the user to click "Submitting transaction" button. This should do the trick.

Will be very grateful if you could take a look.

**Comment by quietbits** [comment]
Thanks for reporting this, @orbitlens ! Sure, we'll look into this sometime this week.

**Comment by quietbits** [comment]
@orbitlens could you please check if the update (https://github.com/stellar/account-viewer-v2/pull/275) works for you? 🤞
