### ISSUE TITLE
Feature Request: StellarExpert Directory integration

### ISSUE THREAD

**Issue by orbitlens** [stellar/account-viewer-v2#274]
While checking digging through the code to troubleshoot another issue, I stumbled upon the [/src/constants/knownAccounts.ts](https://github.com/stellar/account-viewer-v2/blob/master/src/constants/knownAccounts.ts) file.
Is there any reason why you decided to use a static file instead of querying our [Directory API](https://stellar.expert/directory)?

The Directory is community-maintained. It contains information not only about well-known exchanges, but also anchors, custodians, SDF accounts, asset issuers, and malicious accounts that have been spotted in fraudulent activity. Moderators put a lot of effort in keeping it up to date. For example, it contains more accounts marked with "#memo-required" tag than your static file. The API is stable, here is a [description](https://stellar.expert/openapi.html) and [SEP draft](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0037.md). The API endpoint also supports a batch mode which may come in handy for fetching information about multiple accounts, for example, in the operations history list.

This should makes it easier to solve #272

**Comment by quietbits** [comment]
We are using Directory API (it's very helpful!) to get malicious/unsafe accounts ([/src/ducks/flaggedAccounts.ts](https://github.com/stellar/account-viewer-v2/blob/master/src/ducks/flaggedAccounts.ts)). Not sure why we have known accounts static. 🤔 We'll look into this.
