### ISSUE TITLE
 Wrong memo XLM transfer

### ISSUE THREAD

**Issue by Bitmus** [stellar/account-viewer-v2#382]
I entered the memo incorrectly. There should be a leading number "2". Here is my transaction id:

Transaction 61ecfab757ea66577b854e9709c72d4e5766df18a538f373dbfcafed9dd52ec0

- The address and memo are from Coinbase. Thanks!

**Comment by quietbits** [comment]
Hello, @Bitmus! Did the Account Viewer produce the wrong memo or was it a user error? If it is a bug, could you please provide more information?

**Comment by Bitmus** [comment]
User error. I typed the incorrect memo.

Thank you,

Mussie Woldezghi

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by quietbits** [comment]
Hi, @Bitmus, you cannot change the memo of a submitted transaction. Transactions are immutable, which means once they're submitted to the network they can't be changed. Recommend reaching out to the destination accounts holder to see if they can help you.

**Comment by Bitmus** [comment]
Thank you! I was able to find my XLM.

Thank you,

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
